### PR TITLE
add README in Japanese

### PR DESCRIPTION
**Pull request by hoxo-m**
I have translated the README of pipeR into Japanese so as to follow @teramonagi.
https://github.com/renkun-ken/rlist/pull/100

Please check on that.

### CODE REVIEW

**Comment by teramonagi** [comment]
LGTM!!!

**Comment by renkun-ken** [comment]
Thanks! Would you please add some build-ignores to `.Rbuildignore` to ignore `README.ja.md` so that the package can pass the R CMD check?

The following should work.

```
^README.*\.Rmd$
^README\..*\.md$
```

**Comment by hoxo-m** [comment]
I did it.

**Comment by renkun-ken** [comment]
Thanks for your kind contribution!

**Pull request merged**
